import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import PrelineScriptWrapper from './components/PrelineScriptWrapper';
import AppLayout from './components/AppLayout';
import { SidebarProvider } from './components/SidebarContext';

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppLayout>
            {children}
          </AppLayout>
        </SidebarProvider>
        <PrelineScriptWrapper />
      </body>
    </html>
  );
}
