# Generated by Django 5.0.2 on 2025-06-24 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpscreg_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('pubmed_id', models.IntegerField(blank=True, null=True)),
                ('is_curated', models.BooleanField(default=False)),
                ('transcription_status', models.CharField(default='pending', max_length=100)),
                ('transcription_content', models.TextField(blank=True)),
                ('curation_status', models.CharField(default='pending', max_length=100)),
                ('curation_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.curationobject')),
            ],
        ),
    ]
