# Generated by Django 5.0.2 on 2025-06-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_celllinetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celllinetemplate',
            name='CellLine_donor_age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='InducedDerivation_vector_type',
            field=models.CharField(blank=True, choices=[('non-integrated', 'Non-integrated'), ('integrated', 'Integrated'), ('vector-free', 'Vector-free'), ('none', 'None')], max_length=30),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='MicrobiologyVirologyScreening_hep_b',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('neg', 'Negative'), ('not done', 'Not Done')], max_length=20),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='MicrobiologyVirologyScreening_hep_c',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('neg', 'Negative'), ('not done', 'Not Done')], max_length=20),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='MicrobiologyVirologyScreening_hiv1',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('neg', 'Negative'), ('not done', 'Not Done')], max_length=20),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='MicrobiologyVirologyScreening_hiv2',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('neg', 'Negative'), ('not done', 'Not Done')], max_length=20),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='MicrobiologyVirologyScreening_mycoplasma',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('neg', 'Negative'), ('not done', 'Not Done')], max_length=50),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='ReprogrammingMethod_vector_type',
            field=models.CharField(blank=True, choices=[('non-integrated', 'Non-integrated'), ('integrated', 'Integrated'), ('vector-free', 'Vector-free'), ('none', 'None')], max_length=30),
        ),
    ]
