# Generated by Django 5.0.2 on 2025-06-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_celllinetemplate_cellline_donor_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celllinetemplate',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='celllinetemplate',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celllinetemplate',
            name='locked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
