# Generated by Django 5.0.2 on 2025-06-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_locking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('metadata', models.JSONField()),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('cell_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.celllinetemplate')),
            ],
            options={
                'db_table': 'cellline_version',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['cell_line', 'version_number'], name='cellline_ve_cell_li_d4d5da_idx'), models.Index(fields=['created_on'], name='cellline_ve_created_4221e0_idx'), models.Index(fields=['is_archived'], name='cellline_ve_is_arch_e29b0c_idx')],
                'unique_together': {('cell_line', 'version_number')},
            },
        ),
    ]
