# Generated by Django 5.0.2 on 2025-06-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_cellline_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celllinetemplate',
            name='CellLine_donor_sex',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='GenomicAlteration_mutation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='MicrobiologyVirologyScreening_hep_b',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='MicrobiologyVirologyScreening_hep_c',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='MicrobiologyVirologyScreening_hiv1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='MicrobiologyVirologyScreening_hiv2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='MicrobiologyVirologyScreening_mycoplasma',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='PluripotencyCharacterisation_cell_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
