# Generated by Django 5.0.2 on 2025-06-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_choice_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celllinetemplate',
            name='CellLine_cell_line_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='CultureMedium_passage_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='GenomicCharacterisation_karyotype_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='InducedDerivation_vector_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='PluripotencyCharacterisation_differentiation_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='ReprogrammingMethod_vector_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='celllinetemplate',
            name='STRResults_group',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
