# Generated by Django 5.0.2 on 2025-07-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_all_choice_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='curation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='curation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celllinetemplate',
            name='curation_source',
            field=models.CharField(blank=True, choices=[('hpscreg', 'HPSCREG'), ('LLM', 'LLM Generated'), ('institution', 'Institution'), ('manual', 'Manual Entry')], default='manual', max_length=50),
        ),
    ]
