# Generated by Django 5.0.2 on 2025-07-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_curation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscribedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('pubmed_id', models.IntegerField(blank=True, null=True)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transcription_content', models.TextField(blank=True)),
                ('transcription_error', models.TextField(blank=True, null=True)),
                ('curation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('curation_error', models.TextField(blank=True, null=True)),
                ('curation_started_at', models.DateTimeField(blank=True, null=True)),
                ('is_curated', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transcribed Article',
                'verbose_name_plural': 'Transcribed Articles',
                'db_table': 'transcribed_article',
                'ordering': ['-created_on'],
            },
        ),
    ]
