# Generated by Django 5.0.2 on 2025-07-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transcribedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='celllinetemplate',
            name='work_status',
            field=models.CharField(blank=True, choices=[('in progress', 'In Progress'), ('for review', 'For Review'), ('reviewed', 'Reviewed')], default='in progress', max_length=20),
        ),
    ]
