# Generated by Django 5.0.2 on 2025-07-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_work_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='celllinetemplate',
            name='source_article',
            field=models.ForeignKey(blank=True, help_text='The article from which this cell line was curated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_cell_lines', to='api.transcribedarticle'),
        ),
    ]
