"""
Auto-generated Pydantic models for ASCR curation.

Source: 2025_12_ascr_data_dictionary_v1.0.xlsx
Generated by: make_data_dictionary.py
Do not edit manually - regenerate from xlsx source.
"""

from datetime import date, datetime
from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class CellLine(BaseModel):
    __table_name__ = "stem_cell_cellline"

    hpscreg_name: Optional[str] = Field(default=None, max_length=100, description="Cell line name in hPSCreg.")
    cell_line_alt_name: Optional[str] = Field(default=None, max_length=100, description="Alternative name/s for the cell line.")
    cell_type: Literal["human embryonic stem cell (hESC)", "human induced pluripotent stem cell (hiPSC)"] = Field(description="Type of cell line.")
    status: Literal["Backup", "Characterised"] = Field(description="Status of the cell line's characterisation.")
    genotype: Literal["Patient Control", "Gene Corrected"] = Field(description="Summary of overall genotype of the cell line at the genotype_locus.")
    genotype_locus: str = Field(max_length=100, description="Specific gene locus affected by variants or modifications.")
    frozen: bool = Field(description="Describes whether stock of the cell line was frozen.")
    associated_polymorphism: Optional[str] = Field(default=None, description="Known polymorphism/s associated with the cell line.")
    research_use: bool = Field(description="Describes whether the cell line is available for research use.")
    clinical_use: bool = Field(description="Describes whether the cell line is available for clinical use.")
    commercial_use: bool = Field(description="Describes whether the cell line is available for commercial use.")
    certificate_of_pluripotency_characterisation: bool = Field(description="Describes whether a certificate of pluripotency has been issued for the cell line.")
    publish: bool = Field(description="Whether the line can be made visible on ASCR website")
    embargo_date: Optional[date] = Field(default=None, description="Australian Stem Cell Registry embargo date for cell line entry.")
    registered_with_hpscreg: Literal["Not Registered", "Registered", "To be Updated", "Cannot be Registered"] = Field(description="Whether the line can be registered with hPSCreg.")
    curation_status: Literal["Not yet reviewed by Australian Stem Cell Registry", "Reviewed by Australian Stem Cell Registry", "Reviewed and Updated by Australian Stem Cell Registry", "Flagged for further review"] = Field(description="Cell line's curation status in the Australian Stem Cell Registry.")


class ExternalCellLineSource(BaseModel):
    __table_name__ = "stem_cell_externalcelllinesource"

    name: str = Field(max_length=100, description="Name of the external cell line which served as the source cell.")
    xref_url: str = Field(description="URL to source cell line pages in relevant external databases.")
    xref_id: str = Field(max_length=100, description="Identifier for source cell line in relevant external databases.")
    polymorphism: Optional[str] = Field(default=None, max_length=500, description="Known polymorphism/s associated with the source cell line.")
    provider: Optional[str] = Field(default=None, max_length=500, description="Source cell line provider/ company name.")
    provider_cat_num: Optional[str] = Field(default=None, max_length=100, description="Provider catalogue number for source cell line.")
    provider_cat_url: Optional[str] = Field(default=None, description="URL to provider page for source cell line.")
    lot_number: Optional[str] = Field(default=None, max_length=100, description="Provider lot number for source cell line.")


class Contact(BaseModel):
    __table_name__ = "stakeholders_contact"

    first_name: str = Field(max_length=255, description="First name of contact.")
    last_name: str = Field(max_length=255, description="Last name of contact.")
    name_initials: Optional[str] = Field(default=None, max_length=4, description="Initial of contact's middle name.")
    e_mail: str = Field(description="Email address of contact.")
    phone_number: Optional[str] = Field(default=None, max_length=128, description="Phone number of contact.")


class Institute(BaseModel):
    __table_name__ = "stakeholders_institute"

    name: str = Field(max_length=100, description="Name of institution.")
    acronym: Optional[str] = Field(default=None, max_length=8, description="Institute acronym.")
    city: str = Field(max_length=100, description="City of institution.")
    country: str = Field(max_length=80, description="Country of institution.")
    latitude: Optional[float] = Field(default=None, description="Latitude coordinate for institute.")
    longitude: Optional[float] = Field(default=None, description="Longitude coordinate for institute.")


class Group(BaseModel):
    __table_name__ = "stakeholders_group"

    name: str = Field(max_length=100, description="Name of the group.")
    is_research_group: bool = Field(description="Describes whether the group is a research group.")
    institutes: str = Field(description="Django ManyToManyField linking to stakeholders_institute via stakeholders_group_institutes")
    contacts: str = Field(description="Django ManyToManyField linking to stakeholders_contact via stakeholders_group_contacts")


class Ethics(BaseModel):
    __table_name__ = "stem_cell_ethics"

    ethics_number: str = Field(max_length=100, description="Ethics approval number associated with the cell line.")
    approval_date: Optional[date] = Field(default=None, description="Date of ethics approval.")
    consent_form: Optional[str] = Field(default=None, description="Template of donor consent form.")
    consent_for_specific_research: bool = Field(description="Whether consent pertains to a specific research project.")
    consent_for_future_research: bool = Field(description="Whether consent permits unforeseen future research, without further consent.")
    consent_for_global_distribution: bool = Field(description="Whether consent prevents cells derived from the donated biosample from being made available to researchers anywhere in the world.")
    institutional_HREC: Optional[str] = Field(default=None, max_length=500, description="Name of institutional human research ethics committee granting the relevant approval.")


class RegistrationRequirements(BaseModel):
    __table_name__ = "stem_cell_registrationrequirements"

    submitted_ethics_clearance: Literal["Yes", "No", "Unknown"] = Field(description="Describes whether the cell line has HREC approval")


class xRef(BaseModel):
    __table_name__ = "stem_cell_xref"

    db_url: Optional[str] = Field(default=None, description="URL to the home page of the external database the cell line is referenced in.")
    xref_url: str = Field(description="Full URL to the external database entry for the cell line.")
    db_name: str = Field(max_length=100, description="Name of the external database the cell line is referenced in.")


class Publication(BaseModel):
    __table_name__ = "stem_cell_publication"

    doi: str = Field(description="Digital Object Identifier of the publication.")
    pmid: Optional[str] = Field(default=None, max_length=100, description="PubMed ID of the publication.")
    first_author: str = Field(max_length=100, description="Name of first author of the publication.")
    last_author: str = Field(max_length=100, description="Name of last author of the publication.")
    journal: str = Field(max_length=150, description="Name of journal that publication was published in.")
    title: Optional[str] = Field(default=None, max_length=255, description="Title of the publication.")
    year: int = Field(description="Year that publication was published.")


class DonorSource(BaseModel):
    __table_name__ = "stem_cell_donorsource"

    age: Literal["Unknown", "Embryo", "Fetal", "Neonate", "1-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84", "85-89", "89+"] = Field(description="Age range of the donor.")
    sex: Literal["Male", "Female", "Other", "Unknown"] = Field(description="Genetic sex of the donor.")
    polymorphism: Optional[str] = Field(default=None, max_length=500, description="Polymorphism associated with the donor.")
    xref_url: Optional[str] = Field(default=None, description="Full URL to donor related entry in database.")
    xref_id: Optional[str] = Field(default=None, max_length=100, description="Identifier for donor entry in external database.")


class Disease(BaseModel):
    __table_name__ = "stem_cell_disease"

    name: str = Field(max_length=100, description="Disease name as reported unless an ontological label applies.")
    description: str = Field(max_length=1250, description="Disease description.")
    omim_url: str = Field(description="URL for disease entry in OMIM.")
    omim_id: str = Field(max_length=100, description="Identifier for disease entry in OMIM.")
    icd11_url: str = Field(description="URL for disease entry in ICD11.")
    icd11_id: str = Field(max_length=100, description="Identifier for disease entry in ICD11.")


class MediumComponentItems(BaseModel):
    __table_name__ = "stem_cell_mediumcomponentitems"

    name: str = Field(max_length=100, description="Name of media component.")
    amount: Optional[str] = Field(default=None, max_length=20, description="Number of unit/s of component used.")
    unit: Optional[Literal["Percent", "Milliliter", "Microliter", "Millimolar", "Micromolar", "Milligram per milliliter", "Microgram per milliliter", "Nanogram per milliliter", "Nanomolar", "Unit per milliliter", "Unit"]] = Field(default=None, description="Units for media component amount.")
    company: Optional[str] = Field(default=None, max_length=100, description="Name of company who supplied media component.")
    type: Literal["Base Medium", "Main Protein", "Supplement", "Base Coat", "Serum"] = Field(description="Type of media component.")


class CultureMedium(BaseModel):
    __table_name__ = "stem_cell_culturemedium"

    co2_concentration: Optional[float] = Field(default=None, description="CO2 concentration.")
    o2_concentration: Optional[float] = Field(default=None, description="O2 Concentration.")
    rho_kinase_sed: Optional[bool] = Field(default=None, description="Whether Rho Kinase been used at cryo, passage or thaw. ")
    passage_method: Literal["Enzymatically", "Enzyme-free cell dissociation", "Mechanically", "Other", "Not specified"] = Field(description="Method used for passaging cells.")
    other_passage_method: str = Field(max_length=100, description="Other cell passage method (if not covered by passage_method).")
    culture_medium_items: str = Field(description="Django ManyToManyField linking to stem_cell_mediumcomponentitems via stem_cell_culturemedium_culture_medium_items")


class MicrobiologyVirologyScreening(BaseModel):
    __table_name__ = "stem_cell_microbiologyvirologyscreening"

    performed: bool = Field(description="Describes whether any microbiology or virology screening was performed.")
    hiv1: Literal["Positive", "Negative", "Not Done"] = Field(description="HIV1 test result if/ whether available.")
    hiv2: Literal["Positive", "Negative", "Not Done"] = Field(description="HIV2 test result if/ whether available.")
    hep_b: Literal["Positive", "Negative", "Not Done"] = Field(description="Hepatitis B test result if/ whether available.")
    hep_c: Literal["Positive", "Negative", "Not Done"] = Field(description="Hepatitis C test result if/ whether available.")
    mycoplasma: Literal["Positive", "Negative", "Not Done"] = Field(description="Mycoplasma test result if/ whether available.")
    other: Optional[str] = Field(default=None, max_length=100, description="Other microbiology/virology screening test performed if any.")
    other_result: Literal["Positive", "Negative", "Not Done"] = Field(description="Result of other screening test.")


class GenomicAlteration(BaseModel):
    __table_name__ = "stem_cell_genomicalteration"

    mutation_type: Literal["Variant", "Transgene Expression", "Gene Knock-out", "Gene Knock-in", "Isogenic modification"] = Field(description="Type of genomic alteration.")
    cytoband: str = Field(max_length=100, description="Chromosome/cytoband location of genomic alteration.")
    delivery_method: str = Field(max_length=500, description="Delivery method of genomic alteration.")
    description: str = Field(max_length=500, description="Description relevant to genomic alteration.")
    genotype: str = Field(max_length=500, description="Genotype of genomic alteration.")


class CharacterisationProtocolResult(BaseModel):
    __table_name__ = "stem_cell_characterisationprotocolresult"

    cell_type: Literal["Endoderm", "Ectoderm", "Mesoderm", "Trophectoderm"] = Field(description="Type of germ layer into which the stem cell line was differentiated.")
    show_potency: Optional[bool] = Field(default=None, description="Indicates whether the stem cell was shown to differentiate into the germ layer indicated by cell_type.")
    marker_list: Optional[str] = Field(default=None, max_length=100, description="List of markers used to demonstrate differentiation into germ layer.")
    differentiation_profile: Optional[Literal["In vivo teratoma", "In vitro spontaneous differentiation", "In vitro directed differentiation", "Other", "Unknown"]] = Field(default=None, description="Method of differentiation.")
    transcriptome_data_url: Optional[str] = Field(default=None, description="Link to raw transcriptome data relevant to differentiation of stem cell line.")
    morphology_file: Optional[str] = Field(default=None, description="File demonstrating morphology of differentiated cells.")


class UndifferentiatedCharacterisation(BaseModel):
    __table_name__ = "stem_cell_undifferentiatedcharacterisation"

    epi_pluri_test: Optional[bool] = Field(default=None, description="Describes whether EpiPluri Test results are available for undifferentiated cells.")
    epi_pluri_score: Optional[float] = Field(default=None, description="EpiPluri Test Score (for undifferentiated cells).")
    epi_pluri_mcpg: bool = Field(description="EpiPluri mCpG result (undifferentiated cells).")
    epi_pluri_oct4: bool = Field(description="EpiPluri OCT4 methylation result (undifferentiated cells).")
    pluri_test: Optional[bool] = Field(default=None, description="Describes whether PluriTest results are available for undifferentiated cells.")
    pluri_test_score: Optional[float] = Field(default=None, description="Pluritest_score (undifferentiated cells).")
    pluri_novelty_score: Optional[float] = Field(default=None, description="Pluritest_novelty_score (undifferentiated cells).")
    pluri_test_microarray_url: Optional[str] = Field(default=None, description="URL for PluriTest microarray data (undifferentiated cells).")
    morphology_file: Optional[str] = Field(default=None, description="Morphology image file (undifferentiated cells).")
    other: Optional[str] = Field(default=None, max_length=100, description="Describes whether any other tests were performed to characterise undifferentiated cells.")


class HpscScorecard(BaseModel):
    __table_name__ = "stem_cell_hpscscorecard"

    self_renewal: bool = Field(description="hPSC score card self-renewal result (TRUE indicates positive result).")
    endoderm: bool = Field(description="hPSC scorecard endoderm result (TRUE indicates positive result).")
    mesoderm: bool = Field(description="hPSC scorecard mesoderm result (TRUE indicates positive result).")
    ectoderm: bool = Field(description="hPSC scorecard ectoderm result (TRUE indicates positive result).")
    scorecard_file: Optional[str] = Field(default=None, description="hPSC scorecard file.")


class UnDiffCharacterisationExpressionMarkerMethod(BaseModel):
    __table_name__ = "stem_cell_undiffcharacterisationexpressionmarkermethod"

    marker: str = Field(max_length=100, description="Marker used to assess undifferentiated state.")
    method_file: Optional[str] = Field(default=None, description="File containing method or protocol related information (image, data, etc.).")


class CharacterisationMethod(BaseModel):
    __table_name__ = "stem_cell_characterisationmethod"

    description: str = Field(description="Characterisation method description.")
    name: str = Field(max_length=100, description="Characterisation method name.")


class GenomicCharacterisation(BaseModel):
    __table_name__ = "stem_cell_genomiccharacterisation"

    passage_number: Optional[str] = Field(default=None, max_length=10, description="Passage number at which characterisation occurred.")
    karyotyped: Literal["YES", "NO", "UNKNOWN"] = Field(description="Describes whether the line has been karyotyped.")
    karyotype: str = Field(max_length=100, description="Karyotype of the line.")
    karyotype_method: Literal["G-banding", "Q-banding", "Spectral Karyotyping", "Comparative genomic hybridisation", "Array comparative genomic hybridisation", "Molecular karyotyping by SNP array", "Karyolite BoBs", "Exome sequencing", "Methylation profiling", "Other"] = Field(description="Method used to karyotype line.")
    karyotype_method_other: Optional[str] = Field(default=None, max_length=100, description="Other Karyotype method (if not covered by karyotype_method).")
    karyogram: Optional[str] = Field(default=None, description="Karyogram file.")
    summary: str = Field(max_length=1500, description="Text summary of genomic characterisation.")
    data_url: Optional[str] = Field(default=None, description="Data url.")
    data_file: Optional[str] = Field(default=None, description="Data file.")


class AdditionalGenomicCharacterisation(BaseModel):
    __table_name__ = "stem_cell_additionalgenomiccharacterisation"

    hla_typing: bool = Field(description="Describes whether HLA typing was done.")
    str_analysis: bool = Field(description="Describes whether STR analysis was done.")
    fingerprinting_analysis: bool = Field(description="Describes whether fingerprint analysis was done.")
    genome_wide_or_functional_data: bool = Field(description="Describes whether GWAS analysis was done.")


class HlaResult(BaseModel):
    __table_name__ = "stem_cell_hlaresult"

    loci_group: Literal["HLA Class I", "HLA Class II", "Non HLA Genes"] = Field(description="HLA type.")
    allele_1: Optional[str] = Field(default=None, max_length=100, description="First HLA Allele.")
    allele_2: Optional[str] = Field(default=None, max_length=100, description="Second HLA Allele.")


class StrOrFingerprinting(BaseModel):
    __table_name__ = "stem_cell_strorfingerprinting"

    allele_1: Optional[str] = Field(default=None, max_length=100, description="First STR allele at a given locus.")
    allele_2: Optional[str] = Field(default=None, max_length=100, description="Second STR allele at a given locus.")


class Loci(BaseModel):
    __table_name__ = "stem_cell_loci"

    name: str = Field(max_length=100, description="Loci name.")
    chromosome: Optional[str] = Field(default=None, max_length=100, description="Chromome location.")
    start: Optional[int] = Field(default=None, description="Start position.")
    end: Optional[int] = Field(default=None, description="End position.")
    group: Optional[str] = Field(default=None, max_length=100, description="Loci group.")
    ncbi_url: Optional[str] = Field(default=None, description="	Link to NCBI entry.")
    ebi_url: Optional[str] = Field(default=None, description="Link to EBI/Ensembl entry.")


class VectorFreeReprogram(BaseModel):
    __table_name__ = "stem_cell_vectorfreereprogram"

    kit_name: Optional[str] = Field(default=None, max_length=500, description="Name of the commercial kit used for vector-free reprogramming.")
    mrna: bool = Field(description="Indicates whether mRNA was used to induce reprogramming.")
    protein: bool = Field(description="Indicates whether protein was used to induce reprogramming.")
    small_molecule_flag: bool = Field(description="Indicates whether small molecules were used to induce reprogramming.")
    mirna: bool = Field(description="Indicates whether micro-RNA was used to induce reprogramming.")


class IntegratedVector(BaseModel):
    __table_name__ = "stem_cell_integratedvector"

    int_vector_name: str = Field(max_length=100, description="Name of integrating vector.")
    int_rep_vector: Literal["Virus", "Plasmid", "Transposon", "Other"] = Field(description="Type of integrating reprogramming vector.")
    int_rep_vector_other: Optional[str] = Field(default=None, max_length=100, description="Free-text to capture other type of integrating reprogramming vector.")
    int_rep_virus_type: Literal["Adenovirus", "Retrovirus", "Lentivirus", "Other"] = Field(description="Specify virus type if the vector is viral.")
    int_rep_virus_other: Optional[str] = Field(default=None, max_length=100, description="Free-text to capture other type of virus.")
    int_rep_trans_type: Literal["PiggyBac", "Sleeping Beauty", "Other"] = Field(description="System used to deliver the vector.")
    int_rep_trans_type_other: Optional[str] = Field(default=None, max_length=100, description="Free-text to capture other types of system used to deliver the vector.")
    excisable: bool = Field(description="Indicates whether the integrating vector is designed to be excisable.")
    silenced: Literal["Yes", "No", "Unknown"] = Field(description="Indicates whether expression of the reprogramming genes in the vector have been silenced.")
    detected_reprogramming_vector: Literal["Yes", "No", "Unknown"] = Field(description="Was the reprogramming vector detected?")
    detected_vector_notes: Optional[str] = Field(default=None, max_length=500, description="Notes describing how the reprogramming vector was detected.")


class NonIntegratedVector(BaseModel):
    __table_name__ = "stem_cell_nonintegratedvector"

    non_int_vector_name: str = Field(max_length=500, description="Name of non-integrating vector.")
    non_int_vector: Literal["Episomal", "Sendai Virus", "AAV", "Other"] = Field(description="Type of non-integrating vector.")
    non_int_other_vector: Optional[str] = Field(default=None, max_length=500, description="Free-text to capture other type of non-integrating vector.")
    detected_reprogramming_vector: Literal["Yes", "No", "Unknown"] = Field(description="Indicates whether the non-integrating reprogramming vector/s were detected.")
    detected_vector_notes: Optional[str] = Field(default=None, max_length=500, description="Free text field to capture notes regarding how vector detection was performed.")


class CellLineDerivationInducedPluripotent(BaseModel):
    __table_name__ = "stem_cell_celllinederivationinducedpluripotent"

    passage_number: Optional[str] = Field(default=None, max_length=10, description="Passage number at which reprogramming occurred.")
    i_source_cell_type_additional_info: Optional[str] = Field(default=None, max_length=500, description="Free-text entry for additional information about source cell type.")
    i_reprogramming_vector_type: Literal["Not integrated", "Integrated", "None", "Vector free"] = Field(description="Type of vector used for reprogramming.")
    vector_map_file: Optional[str] = Field(default=None, description="	Vector plasmid map file.")
    method_used_immune_marker_staining: bool = Field(description="Was immune marker staining used to show that the reprogramming vector was not detected?")
    method_used_pcr: bool = Field(description="Was pcr used to show that the reprogramming vector was not detected?")
    method_used_rtpcr: bool = Field(description="Was RT-PCR used to show that the reprogramming vector was not detected?")
    method_used_seq: bool = Field(description="Was sequencing used to show that the reprogramming vector was not detected?")
    reprogramming_expression_silence_file: Optional[str] = Field(default=None, description="File showing silencing of reprogramming gene expression.")
    derivation_year: Optional[date] = Field(default=None, description="Year in which the ipsc was derived.")
    reason_no_derivation_year: Optional[str] = Field(default=None, max_length=500, description="Text explanation if the year of derivation is unknown.")
    selection_criteria_for_clones: Optional[str] = Field(default=None, max_length=500, description="Description of how iPSC clones were selected.")
    derived_under_xeno_free_conditions: Optional[bool] = Field(default=None, description="Indicates whether derivation of the ipsc was performed without animal products.")
    derivation_under_gmp: Optional[bool] = Field(default=None, description="Indicates whether derivation of the ipsc followed Good Manufacturing Practice.")
    available_as_clinical_grade: bool = Field(description="Indicates if the ipsc cell line is available as clinical-grade.")
    gene_list: str = Field(description="Django ManyToManyField linking to stem_cell_loci through stem_cell_idpgene.")


class CellLineDerivationEmbryonic(BaseModel):
    __table_name__ = "stem_cell_celllinederivationembryonic"

    e_nhmrc_licence_number: Optional[str] = Field(default=None, max_length=100, description="NHMRC License number.")
    e_preimplant_genetic_diagnosis: bool = Field(description="Indicates whether the cell line was derived from a preimplantation genetic diagnostic embryo.")
    e_supernumerary: bool = Field(description="Indicates whether the embryo used was a supernumerary embryo from IVF treatment.")
    derivation_year: Optional[date] = Field(default=None, description="Year in which the ESC was derived (ie. cells isolated from embryo).")
    reason_no_derivation_year: Optional[str] = Field(default=None, max_length=100, description="Text explanation if the year of derivation is unknown.")
    separation_of_research_and_ivf_treat: Optional[bool] = Field(default=None, description="Describes whether IVF treatment and research decision-making processes were clearly separated.")
    other_hesc_source: Literal["Somatic Cell Nuclear Transfer (SCNT)", "Pathogenesis", "Other"] = Field(description="Indicates if the hESC line was derived from a source other than supernumerary IVF embryos.")
    other_hesc_source_other: Optional[str] = Field(default=None, max_length=100, description="Description of other embryo source.")
    embryo_stage: Optional[Literal["Blastula with ICM and Trophoblast", "Cleavage (Mitosis)", "Compaction", "Morula", "Zygot"]] = Field(default=None, description="Developmental stage of the embryo at the time of cell isolation.")
    expansion_status: Optional[Literal["Stage 1", "Stage 2", "Stage 3", "Stage 4", "Stage 5", "Stage 6"]] = Field(default=None, description="	Indicates the extent to which the cell line has undergone expansion.")
    icm_morphology: Optional[Literal["Type A", "Type B", "Type C", "Type D", "Type E"]] = Field(default=None, description="Morphological quality of the inner cell mass (ICM) used in derivation.")
    trophectoderm_morphology: Optional[Literal["Type A", "Type B", "Type G"]] = Field(default=None, description="Morphology of the trophectoderm layer at the time of derivation.")
    zp_removal_technique: Literal["Chemical", "Enzymatic", "Manual", "Mechanical", "Spontaneous", "Other"] = Field(description="Technique used to remove the zona pellucida (ZP).")
    zp_removal_technique_other: Optional[str] = Field(default=None, max_length=100, description="	Free-text entry for other techniques to remove ZP.")
    cell_isolation: Literal["Immunosurgery", "Laser", "mechanical trophectoderm and icm isolated", "None", "Other"] = Field(description="Method used to isolate cells from embryo.")
    cell_isolation_other: Optional[str] = Field(default=None, max_length=100, description="Free-text entry for other method used to isolate cells from embryo.")
    cell_seeding: Literal["Embryo", "Isolated ICM", "Single cell", "Other"] = Field(description="Technique used to plate cells post-isolation.")
    cell_seeding_other: Optional[str] = Field(default=None, max_length=100, description="Free-text entry for other technique used to plate cells post-isolation.")
    derived_under_gmp: Optional[bool] = Field(default=None, description="Indicates whether derivation followed Good Manufacturing Practice.")
    derived_under_xeno_free_conditions: Optional[bool] = Field(default=None, description="Indicates whether the derivation was performed without animal products.")
    available_as_clinical_grade: Optional[bool] = Field(default=None, description="Indicates if the resulting cell line is available as clinical-grade.")


class Synonym(BaseModel):
    __table_name__ = "stem_cell_synonym"

    synonym: str = Field(max_length=100, description="Cell line synonym.")


class IdpGene(BaseModel):
    __table_name__ = "stem_cell_idpgene"

    allele_1: Optional[str] = Field(default=None, max_length=100, description="First allele observed at gene locus.")
    allele_2: Optional[str] = Field(default=None, max_length=100, description="Second allele observed at gene locus.")


class VectorFreeReprogrammingGenes(BaseModel):
    __table_name__ = "stem_cell_vectorfreereprogramminggenes"

    nv_type: Literal["mRNA", "Protein"] = Field(description="Type of genomic feature.")
    allele_1: Optional[str] = Field(default=None, max_length=100, description="First allele observed at gene locus.")
    allele_2: Optional[str] = Field(default=None, max_length=100, description="Second allele observed at gene locus.")


class SmallMolecule(BaseModel):
    __table_name__ = "stem_cell_smallmolecule"

    name: str = Field(description="Small molecule name")
    chembank_id: Optional[str] = Field(default=None, description="Chembank database id for the small molecule")


class Ontology(BaseModel):
    __table_name__ = "ontologies_ontology"

    label: str = Field(max_length=1000, description="Text label for ontology_identifier.")
    definition: Optional[str] = Field(default=None, description="Definition of ontology term (label).")
    ontology_db_name: str = Field(max_length=100, description="Name of ontology database.")
    url: str = Field(description="URL to web entry for ontology_identifier.")
    lowest_level_for_search: bool = Field(description="Describes whether the ontology_id is used as the lowest level for filtering and searching.")


class Synonyms(BaseModel):
    __table_name__ = "ontologies_synonyms"

    synonym: str = Field(max_length=1000, description="Synonyms of ontology label.")


class CellLineCurationForm(BaseModel):
    """Composite model containing all cell line curation data."""
    cell_line: List[CellLine] = Field(default_factory=list)
    external_cell_line_source: List[ExternalCellLineSource] = Field(default_factory=list)
    contact: List[Contact] = Field(default_factory=list)
    institute: List[Institute] = Field(default_factory=list)
    group: List[Group] = Field(default_factory=list)
    ethics: List[Ethics] = Field(default_factory=list)
    registration_requirements: List[RegistrationRequirements] = Field(default_factory=list)
    x_ref: List[xRef] = Field(default_factory=list)
    publication: List[Publication] = Field(default_factory=list)
    donor_source: List[DonorSource] = Field(default_factory=list)
    disease: List[Disease] = Field(default_factory=list)
    medium_component_items: List[MediumComponentItems] = Field(default_factory=list)
    culture_medium: List[CultureMedium] = Field(default_factory=list)
    microbiology_virology_screening: List[MicrobiologyVirologyScreening] = Field(default_factory=list)
    genomic_alteration: List[GenomicAlteration] = Field(default_factory=list)
    characterisation_protocol_result: List[CharacterisationProtocolResult] = Field(default_factory=list)
    undifferentiated_characterisation: List[UndifferentiatedCharacterisation] = Field(default_factory=list)
    hpsc_scorecard: List[HpscScorecard] = Field(default_factory=list)
    un_diff_characterisation_expression_marker_method: List[UnDiffCharacterisationExpressionMarkerMethod] = Field(default_factory=list)
    characterisation_method: List[CharacterisationMethod] = Field(default_factory=list)
    genomic_characterisation: List[GenomicCharacterisation] = Field(default_factory=list)
    additional_genomic_characterisation: List[AdditionalGenomicCharacterisation] = Field(default_factory=list)
    hla_result: List[HlaResult] = Field(default_factory=list)
    str_or_fingerprinting: List[StrOrFingerprinting] = Field(default_factory=list)
    loci: List[Loci] = Field(default_factory=list)
    vector_free_reprogram: List[VectorFreeReprogram] = Field(default_factory=list)
    integrated_vector: List[IntegratedVector] = Field(default_factory=list)
    non_integrated_vector: List[NonIntegratedVector] = Field(default_factory=list)
    cell_line_derivation_induced_pluripotent: List[CellLineDerivationInducedPluripotent] = Field(default_factory=list)
    cell_line_derivation_embryonic: List[CellLineDerivationEmbryonic] = Field(default_factory=list)
    synonym: List[Synonym] = Field(default_factory=list)
    idp_gene: List[IdpGene] = Field(default_factory=list)
    vector_free_reprogramming_genes: List[VectorFreeReprogrammingGenes] = Field(default_factory=list)
    small_molecule: List[SmallMolecule] = Field(default_factory=list)
    ontology: List[Ontology] = Field(default_factory=list)
    synonyms: List[Synonyms] = Field(default_factory=list)

