name: Build and Deploy Docs

on:
  push:
    branches: [ "master" ]  # Runs whenever you push to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir -p output
          for file in *.md; do
            pandoc "$file" -s -c style.css -o "output/${file%.md}.html"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
