name: Build and Deploy Documentation

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docs/**'
      - 'data_dictionary/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install pydantic

      - name: Generate documentation
        run: |
          cd data_dictionary
          python generate_markdown_docs.py

      - name: Setup Pandoc
        uses: pandoc/actions/setup@main
        with:
          version: '3.1.8'

      - name: Create beautiful HTML
        run: |
          mkdir -p _site
          
          # Create a beautiful CSS file for styling
          cat > _site/style.css << 'EOF'
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
            color: #333;
            background-color: #fafafa;
          }
          
          h1, h2, h3, h4, h5, h6 {
            color: #2c3e50;
            margin-top: 2rem;
            margin-bottom: 1rem;
          }
          
          h1 {
            border-bottom: 3px solid #3498db;
            padding-bottom: 0.5rem;
            font-size: 2.5rem;
          }
          
          h2 {
            border-bottom: 2px solid #e74c3c;
            padding-bottom: 0.3rem;
            font-size: 2rem;
          }
          
          h3 {
            border-left: 4px solid #f39c12;
            padding-left: 1rem;
            font-size: 1.5rem;
          }
          
          table {
            width: 100%;
            border-collapse: collapse;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            table-layout: fixed;
          }
          
          th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
            width: 11.11%; /* Equal width for 9 columns */
            word-wrap: break-word;
            overflow-wrap: break-word;
            hyphens: auto;
          }
          
          th {
            background-color: #34495e;
            color: white;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.85rem;
            letter-spacing: 0.5px;
          }
          
          tr:nth-child(even) {
            background-color: #f8f9fa;
          }
          
          tr:hover {
            background-color: #e8f4fd;
            transition: background-color 0.3s ease;
          }
          
          code {
            background-color: #f1f1f1;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Monaco', 'Consolas', monospace;
            font-size: 0.9em;
          }
          
          blockquote {
            border-left: 4px solid #3498db;
            margin: 0;
            padding: 1rem 1.5rem;
            background-color: #f8f9fa;
            border-radius: 0 4px 4px 0;
            font-style: italic;
          }
          
          a {
            color: #3498db;
            text-decoration: none;
          }
          
          a:hover {
            color: #2980b9;
            text-decoration: underline;
          }
          
          .toc {
            background: white;
            padding: 1.5rem;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            margin: 2rem 0;
          }
          
          .toc ul {
            list-style-type: none;
            padding-left: 0;
          }
          
          .toc li {
            margin: 0.5rem 0;
          }
          
          .header-meta {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 2rem;
            border-radius: 12px;
            margin-bottom: 2rem;
            text-align: center;
          }
          
          .stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            margin: 2rem 0;
          }
          
          .stat-card {
            background: white;
            padding: 1.5rem;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            text-align: center;
          }
          
          .stat-number {
            font-size: 2rem;
            font-weight: bold;
            color: #3498db;
          }
          
          .stat-label {
            color: #7f8c8d;
            font-size: 0.9rem;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          
          .table-container {
            overflow-x: auto;
            margin: 1.5rem 0;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
          }
          
          @media (max-width: 768px) {
            body {
              padding: 1rem;
            }
            
            table {
              font-size: 0.75rem;
              min-width: 800px; /* Ensure table doesn't compress too much */
            }
            
            th, td {
              padding: 6px;
            }
          }
          EOF
          
          # Convert markdown to HTML with custom styling
          pandoc docs/data_dictionary.md \
            --standalone \
            --css style.css \
            --metadata title="ASCR Data Dictionary" \
            --metadata author="Australian Stem Cell Registry" \
            --metadata date="$(date +'%B %d, %Y')" \
            --table-of-contents \
            --toc-depth=2 \
            --html-q-tags \
            --highlight-style=tango \
            -o _site/index.html
          
          # Create a simple landing page if needed
          echo "Documentation built successfully at $(date)"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4